### ISSUE TITLE
Authentication needed... but definitely passed

### ISSUE THREAD

**Issue by iDevelopThings** [PetterKraabol/laravel-twitch-api#5] opened 2016-11-12 23:48 UTC
So, this is the snippet I'm using;

```

\TwitchApi::setToken($user->channel->token);
		$update = \TwitchApi::updateChannel($user->channel->display_name, [
			'title' => $request->title,
		], $user->channel->token);


```

My token is definitely set, and as you can see I also try to force it with setToken... but had no luck.

Regardless I receive 
"RequestRequiresAuthenticationException in Api.php line 111:
Request requires authentication"

**Comment by PetterKraabol** [comment] 2016-11-13 00:24
I can confirm I'm having the same issues. Looking into it now.

**Comment by PetterKraabol** [comment] 2016-11-13 00:40
Issue appears on [this line](https://github.com/PetterKraabol/laravel-twitch-api/blob/3dc6a408e493243ab423b40fa1e40ab907701ab4/src/API/Api.php#L35).

`public function __construct($clientId = null, $token = null)`
should be
`public function __construct($token = null, $clientId = null)`

I'll check if this breaks anything before updating. In the meantime, you can change this manually in `/vendor/zarlach/laravel-twitch-api/src/API/Api.php`.

There also seems to be an issue handling $options (parameters such as 'status', 'game', etc when updating a channel) in `Api.php`, I'll look into this.

**Comment by PetterKraabol** [comment] 2016-11-13 01:27
I've fixed the `$options` issue locally. I'll check if this breaks anything else tomorrow. In the meantime, this is how you fix it:

Replace [this foreach loop ](https://github.com/PetterKraabol/laravel-twitch-api/blob/3dc6a408e493243ab423b40fa1e40ab907701ab4/src/API/Api.php#L182-L186) with this one

``` php
foreach ($options as $name => $option) {
    foreach ($option as $key => $value) {
        $url .= (parse_url($url, PHP_URL_QUERY) ? '&' : '?').$name.'['.$key.']='.$value;
    }
}
```

Replace [these variables](https://github.com/PetterKraabol/laravel-twitch-api/blob/003e9a11d52484b6e6470862ccc0b6bcea9e0204/src/API/Channels.php#L40-L41) with these

``` php
$availableOptions = ['channel' => ['status', 'game', 'delay']];
$options = ['channel' => $options];
```

To update channel _(please note that it's 'status' and not 'title')_

``` php
TwitchApi::setToken($someToken);
TwitchApi::updateChannel('zarlach', ['status' => 'Awesome title', 'game' => 'League of Legends']);
```

**Comment by iDevelopThings** [comment] 2016-11-13 11:37
Thanks for the swift response, I'll try this in a couple of hours :)

**Comment by PetterKraabol** [comment] 2016-11-13 14:24
The fix above does break other functions, including authentication, however, it's all fixed in [1.3.3](https://github.com/PetterKraabol/laravel-twitch-api/releases/tag/1.3.3)!

*If you've already made changes to some files locally and the update fails (like it did to me), make sure to close any open laravel-twitch-api files, then `composer update`.*

**Comment by PetterKraabol** [comment] 2016-11-13 14:24
The fix above does break other functions, including authentication, however, it's all fixed in [1.3.3](https://github.com/PetterKraabol/laravel-twitch-api/releases/tag/1.3.3)!

_If you've already made changes to some files locally and the update fails (like it did to me), make sure to close any open laravel-twitch-api files, then `composer update`._

**Closed as completed by PetterKraabol** 2016-11-13 14:24 UTC

**Comment by iDevelopThings** [comment] 2016-11-13 14:53
Thats awesome thank you. I just tested and it works fine :) 

One more issue I forgot about, the cursor is missing from the availibleOptions in channelFollows() 

Update:

Updating worked the first time.. then after for some reason never worked again. Not sure why neither hmm

**Comment by PetterKraabol** [comment] 2016-11-13 15:31
`$availableOptions` [isn't used anymore](https://github.com/PetterKraabol/laravel-twitch-api/blob/a3e9859609df0b0041a100756739c02cc97f3b33/src/API/Api.php#L142-L147). Anything you put in `$options` is sent to Twitch.

Make sure you're using `TwitchApi::followers($name)` and not `TwitchApi::channelFollows()`. There are some function name inconsistencies.
`TwitchApi::followers('zarlach', ['cursor' => '1458786849892131000']);` works just fine for me.

If you're still having problems updating, try completely reinstalling laravel-twitch-api with composer.

``` bash
composer remove zarlach/laravel-twitch-api --no-scripts
```

``` bash
composer require zarlach/laravel-twitch-api --no-scripts
```
